
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lutstmiitytmvxmaorkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1dHN0bWlpdHl0bXZ4bWFvcmtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzE3NDUsImV4cCI6MjA1OTk0Nzc0NX0.T0EHIzWMvsxmS2bJEh3G9A9seyb8gNnHzSS8GgLRUGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'campus-catalyst-auth',
    storage: localStorage,
    detectSessionInUrl: true
  }
});
